name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        php:
          - '8.4'

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl, sodium, fileinfo
          coverage: none

      - uses: ramsey/composer-install@v3

      - run: composer validate --no-check-lock --strict
      - run: composer analyse
      - run: composer format:test
      - run: composer test
      - run: composer test:discovery:install
      - run: composer test:discovery
